// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Decrypter","status":true,"description":"仿mv加密","parameters":{"Decrypter":"1.0","miyao":"测试","mode":"true","dir":"encrypt/","encryptList":"[\"img\",\"audio\",\"data\",\"js/plugins\"]","encryptExt":"{ \"ogg\": \"rmo\", \"m4a\": \"rmm\", \"png\": \"rmp\", \"js\": \"rmj\", \"json\": \"rmd\" }","encryptType":"{ \"ogg\": \"b\", \"m4a\": \"b\", \"png\": \"b\", \"js\": \"t\", \"json\": \"t\" }","plugins":"plugins.js","ignoreList":"[]","weburl":"https://raw.githubusercontent.com/wangwangxingao/world/master","listname":"updateList.json"}}
];
