// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"xingzoutu","status":false,"description":"xp行走图兼容","parameters":{"XPMVCharacter":"汪汪","xp":"xp"}},
{"name":"lizi","status":false,"description":"","parameters":{}},
{"name":"three","status":false,"description":"","parameters":{}},
{"name":"2d-3d","status":false,"description":"","parameters":{}},
{"name":"datgui","status":false,"description":"","parameters":{}},
{"name":"showsprite","status":false,"description":"","parameters":{}},
{"name":"deeplearn","status":false,"description":"","parameters":{}},
{"name":"Record","status":false,"description":"录像","parameters":{"Record":"汪汪"}},
{"name":"show","status":true,"description":"","parameters":{}}
];
