// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins = [
    { "name": "pluginsstart", "status": true, "description": "", "parameters": {} },
    { "name": "pluginsing", "status": true, "description": "", "parameters": {} },
    { "name": "pluginsend", "status": true, "description": "", "parameters": {} }

];